### ISSUE TITLE
freq_to_sp documentation is wrong + some wrong mapping

### ISSUE THREAD

**Issue by ion-elgreco** [descendant-ai/functime#11]
Some offsets are suggested in the documentation, but those will simply return errors: (1ns, 1us for example). Also, the alias_to_sp are not correctly mapped as in the shared link, 30m is wrong, also m is minute, but then in alias_to_sp it is monthly..

**Comment by topher-lo** [comment]
Thanks @ion-elgreco for the report! Should be resolved by https://github.com/descendant-ai/functime/commit/b01ed97fe62def8285281fabd1c6aa0dd417d15c
