### ISSUE TITLE
Rationale for the licensing 

### ISSUE THREAD

**Issue by fclesio** [descendant-ai/functime#12]
First of all, thanks for the great work to provide such a blazing-fast library for Time Series forecasting. I think `functime` comes in a very great timing in the Python libraries space for such kind of problem space. 

I would like to know which rationale used by you that ended up [setting the library as AGPLv3 ](https://github.com/descendant-ai/functime/blob/main/LICENSE)(Affero General Public License v3.0)?

The reason of my question is that most of libraries on that Time Series space has a distinct licensing:

### Apache-2.0 license
- [zillow/luminaire](https://github.com/zillow/luminaire)
- [unit8co/darts](https://github.com/unit8co/darts)
- [Nixtla/mlforecast](https://github.com/Nixtla/mlforecast)
- [Nixtla/statsforecast](https://github.com/Nixtla/statsforecast)
- [Nixtla/hierarchicalforecast](https://github.com/Nixtla/hierarchicalforecast)

### MIT license
- [jdb78/pytorch-forecasting](https://github.com/jdb78/pytorch-forecasting)
- [facebookresearch/Kats](https://github.com/facebookresearch/Kats )
- [facebook/prophet](https://github.com/facebook/prophet )
- [blue-yonder/tsfresh](https://github.com/blue-yonder/tsfresh)

### BSD-3-Clause license
- [sktime/sktime](https://github.com/sktime/sktime)

**Comment by topher-lo** [comment]
We are small team at an early stage startup.

If you have a real commercial use case for functime and want a more permissive OSS license, I am more than happy to grant it.

Just shoot me an email: chris@functime.ai

**Comment by fclesio** [comment]
Thanks for the prompt response and makes completely sense to in that path from that standpoint. 

I do not have a commercial use at the moment, I was just curious because that's was the first thing that popped to my eye reading the main README.md. 

All the success for you folks and have a great day, and once again thanks for the great library.

**Comment by topher-lo** [comment]
We are now Apache 2.0!
