### ISSUE TITLE
Sdist

### ISSUE THREAD

**Issue by thewchan** [descendant-ai/functime#23]
Is it possible to publish sdist archive on PyPI or make a release here on Github (either way if fine)? This looks like a great package that we can make available on Conda Forge but they do need an sdist

**Comment by topher-lo** [comment]
That sounds like a great idea! My team has a tight release schedule for the next 2-3 weeks. Would you be interested in opening an PR for this? We use currently use setuptools as our build system.

Note: we will be adding Rust bindings soon and moving over to Maturin. But will be good to get conda CI up regardless.

**Comment by topher-lo** [comment]
@thewchan Sounds good. We do have this in the backlog (approx. in 2-3 weeks time). Is your request mission critical?

**Comment by topher-lo** [comment]
Resolved by https://github.com/descendant-ai/functime/commit/b8c3063d9d1ed870f59d7ed64d3aed11be385899
