### ISSUE TITLE
TypeError: date_range() got an unexpected keyword argument 'eager'

### ISSUE THREAD

**Issue by markxbaker** [descendant-ai/functime#8]
Ran the example forecasting code on colab, to eager:)?

TypeError                                 Traceback (most recent call last)
[<ipython-input-6-01ebfceac9d9>](https://localhost:8080/#) in <cell line: 16>()
     14 model = lightgbm(freq="1mo", lags=24, max_horizons=3, strategy="ensemble")
     15 model.fit(y=y_train)
---> 16 y_pred = model.predict(fh=3)
     17 
     18 # functime ❤️ functional design

2 frames
[/usr/local/lib/python3.10/dist-packages/polars/utils/decorators.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
     35         def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     36             _rename_kwargs(function.__name__, kwargs, aliases)
---> 37             return function(*args, **kwargs)
     38 
     39         return wrapper

TypeError: date_range() got an unexpected keyword argument 'eager'

**Comment by topher-lo** [comment]
What polars version are you on? The latest Polars version `pl.date_range` as the eager kwarg: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.date_range.html

**Comment by topher-lo** [comment]
FYI @markxbaker we test `quickstart.py` in CI https://github.com/descendant-ai/functime/actions/runs/5589181849

**Comment by topher-lo** [comment]
Resolved by 894981a0d5b24365acdb7f040ae96e49d4ce7a3e
