### ISSUE TITLE
add entity column parameter to all cross_validation functions

### ISSUE THREAD

**Issue by ion-elgreco** [descendant-ai/functime#9]
Currently train_test_split and other functions automatically infer what the entity column is by just picking the first column. Seems to be a crude way of doing that. Being able to add which columns to be used could be more practical.

**Comment by topher-lo** [comment]
https://docs.functime.ai/#quick-examples

We only support panel data where the first two columns are (entity, time). This column order invariant IMO is much easier to reason about than all other alternatives.

**Comment by ion-elgreco** [comment]
> https://docs.functime.ai/#quick-examples
> 
> We only support panel data where the first two columns are (entity, time). This column order invariant IMO is much easier to reason about than all other alternatives.

I would say the opposite because now the requirement is to put the columns in the right order each time and create structs if you want to pass multi column, even though this could be easily passed through the cv functions into groupby.
